import type { Estimate, Job, Opportunity } from "@/types";

export const opportunities: Opportunity[] = [
  {
    id: "b-2604",
    jobId: "Q-26-001",
    month: "April",
    client: "Sundt",
    projectName: "Mesa Public Library Casework",
    bidDueDate: "2026-05-21",
    drawingStage: "CD",
    bidType: "Invited",
    sentDate: "2026-05-07",
    submissionMethod: "Email",
    status: "Submitted",
    winLoss: "",
    jobType: "Casework",
    estimatedValue: 248500,
    links: { drawings: "#", specs: "#", schedule: "#" },
    notes: "Waiting on GC response. Good fit for summer shop load.",
    bidFeedback: "Requested VE alternate for plastic laminate counters.",
    ntpReceived: false,
    initialContractValue: null,
    finalCost: null,
    files: []
  },
  {
    id: "b-2605",
    jobId: "Q-26-002",
    month: "May",
    client: "McCarthy",
    projectName: "Mountain View Science Lab",
    bidDueDate: "2026-06-03",
    drawingStage: "DD",
    bidType: "Budget",
    sentDate: "",
    submissionMethod: "Portal",
    status: "Pricing",
    winLoss: "",
    jobType: "Lab Casework",
    estimatedValue: 410000,
    links: { drawings: "#", specs: "#", schedule: "" },
    notes: "Large scope, spec needs review for AWI grade and hardware assumptions.",
    bidFeedback: "",
    ntpReceived: false,
    initialContractValue: null,
    finalCost: null,
    files: []
  },
  {
    id: "b-2606",
    jobId: "Q-26-003",
    month: "May",
    client: "Layton",
    projectName: "Avondale High School Media Center",
    bidDueDate: "2026-05-14",
    drawingStage: "IFC",
    bidType: "Invited",
    sentDate: "",
    submissionMethod: "Email",
    status: "Lead / ITB",
    winLoss: "",
    jobType: "Education",
    estimatedValue: 292000,
    links: { drawings: "#", specs: "#", schedule: "#" },
    notes: "Fresh ITB. Confirm scope split before takeoff.",
    bidFeedback: "",
    ntpReceived: false,
    initialContractValue: null,
    finalCost: null,
    files: []
  },
  {
    id: "b-2607",
    jobId: "Q-26-004",
    month: "May",
    client: "Ryan Companies",
    projectName: "Desert Ridge Amenity Building",
    bidDueDate: "2026-05-18",
    drawingStage: "CD",
    bidType: "Negotiated",
    sentDate: "",
    submissionMethod: "Portal",
    status: "Review / Send",
    winLoss: "",
    jobType: "Commercial",
    estimatedValue: 168400,
    links: { drawings: "#", specs: "#", schedule: "" },
    notes: "Need final review on alternates before sending.",
    bidFeedback: "",
    ntpReceived: false,
    initialContractValue: null,
    finalCost: null,
    files: []
  },
  {
    id: "b-2528",
    jobId: "Q-25-028",
    month: "December",
    client: "Okland",
    projectName: "North Clinic TI",
    bidDueDate: "2025-12-19",
    drawingStage: "IFC",
    bidType: "Hard Bid",
    sentDate: "2025-12-18",
    submissionMethod: "BuildingConnected",
    status: "Cold",
    winLoss: "",
    jobType: "Medical",
    estimatedValue: 185250,
    links: { drawings: "#", specs: "#", schedule: "#" },
    notes: "Cold but not dead. Follow up each quarter.",
    bidFeedback: "Owner delayed funding.",
    ntpReceived: false,
    initialContractValue: null,
    finalCost: null,
    files: []
  },
  {
    id: "b-2520",
    jobId: "Q-25-020",
    month: "November",
    client: "DPR",
    projectName: "Tempe Student Union",
    bidDueDate: "2025-11-11",
    drawingStage: "IFC",
    bidType: "Negotiated",
    sentDate: "2025-11-09",
    submissionMethod: "Email",
    status: "Won",
    winLoss: "Won",
    jobType: "Commercial",
    estimatedValue: 326000,
    links: { drawings: "#", specs: "#", schedule: "#" },
    notes: "Converted to job G26-042.",
    bidFeedback: "Won on schedule and VE response.",
    ntpReceived: true,
    initialContractValue: 326000,
    finalCost: 271300
  }
];

export const estimates: Estimate[] = [
  {
    id: "est-2604",
    opportunityId: "b-2604",
    documentType: "Proposal",
    proposalNumber: "Q-26-004",
    revision: "0",
    projectName: "Mesa Public Library Casework",
    projectLocation: "Mesa, AZ",
    client: "Sundt",
    clientAddress: "2620 S 55th St\nTempe, AZ 85282",
    clientContact: "Estimating Team",
    architect: "SmithGroup",
    estimator: "Evan Ramsey",
    bidDate: "2026-05-07",
    deliveryDate: "TBD",
    shipVia: "Truck",
    poNumber: "n/a",
    projectId: "Q-26-004",
    bidDocuments: "Permit Set",
    drawingsDated: "05/01/26",
    validDays: 30,
    paymentTerms: "Net 30",
    leadTime: "TBD after approved submittals",
    scopeSummary: "Mesa Public Library Casework",
    pricingMode: "byarea",
    ohPct: 12,
    delPct: 3,
    insPct: 8,
    areas: [
      {
        id: "area-1",
        name: "Level 1",
        qty: 1,
        sections: [
          {
            id: "sec-1",
            name: "Reception",
            items: [
              { id: "item-1", name: "PL reception desk", qty: 28, unit: "lin. ft", unitCost: 425 },
              { id: "item-2", name: "Solid surface top", qty: 64, unit: "sq. ft", unitCost: 92 }
            ]
          },
          {
            id: "sec-2",
            name: "Workroom",
            items: [{ id: "item-3", name: "Base cabinets", qty: 44, unit: "lin. ft", unitCost: 310 }]
          }
        ]
      },
      {
        id: "area-2",
        name: "Level 2",
        qty: 1,
        sections: [
          {
            id: "sec-3",
            name: "Reading room",
            items: [{ id: "item-4", name: "Display shelving", qty: 18, unit: "each", unitCost: 780 }]
          }
        ]
      }
    ],
    subItems: [{ description: "Stone slab allowance", cost: 12500, markupPct: 15 }],
    alternates: [{ description: "Alt 1: Add transaction glass", amount: 8600 }],
    exclusions: ["Electrical, plumbing, and backing by others.", "After-hours installation excluded."],
    clarifications: ["Pricing based on drawings dated 05/01/2026.", "Laminate selections assumed standard Wilsonart group 1."]
  }
];

export const jobs: Job[] = [
  {
    id: "job-g042",
    jobNumber: "G26-042",
    workType: "Bid / ITB",
    pm: "Geoff",
    client: "DPR",
    projectName: "Tempe Student Union",
    baseContract: 326000,
    bidRef: "B-2520",
    awardDate: "2026-03-18",
    ntpDate: "2026-03-18",
    backlogStatus: "Installed",
    forecastStart: "2026-06-17",
    forecastEnd: "2026-06-28",
    forecastQuarter: "Q2 2026",
    expectedFabStart: "2026-05-12",
    expectedCompletion: "2026-06-30",
    fabStatus: "In Fabrication",
    installStart: "2026-06-17",
    installEnd: "2026-06-28",
    installStatus: "Ready",
    invoiceStatus: "Partial",
    crewSize: 5,
    gc: "DPR",
    notes: "Coordinate loading dock schedule before install.",
    finalCost: 271300,
    changeOrders: [
      {
        id: "co-1",
        jobId: "job-g042",
        number: "CO-001",
        description: "Add mailroom cabinets",
        amount: 12400,
        status: "approved",
        dateSubmitted: "2026-04-15",
        approvedDate: "2026-04-21"
      },
      {
        id: "co-2",
        jobId: "job-g042",
        number: "CO-002",
        description: "Revise reception finish",
        amount: 5800,
        status: "submitted",
        dateSubmitted: "2026-05-02"
      }
    ],
    purchaseOrders: [
      {
        id: "po-g042-001",
        jobId: "job-g042",
        poNumber: "PO-G26-042-001",
        vendor: "Arizona Tile & Stone",
        scope: "Stone / Quartz",
        description: "Template, furnish, fabricate, and install quartz tops at student union counters.",
        status: "In Progress",
        committedAmount: 18500,
        approvedChangeAmount: 2200,
        invoicedAmount: 9000,
        paidAmount: 4500,
        issueDate: "2026-04-02",
        neededBy: "2026-05-20",
        promisedDate: "2026-05-22",
        owner: "Geoff",
        notes: "Includes sink cutouts and eased edge profile."
      },
      {
        id: "po-g042-002",
        jobId: "job-g042",
        poNumber: "PO-G26-042-002",
        vendor: "Cambria Certified Fabricator",
        scope: "Cambria",
        description: "Cambria allowance for alternate reception top finish.",
        status: "Draft",
        committedAmount: 7800,
        invoicedAmount: 0,
        paidAmount: 0,
        neededBy: "2026-05-28",
        promisedDate: "2026-06-03",
        owner: "Geoff",
        notes: "Hold until finish selection is confirmed."
      }
    ],
    submittals: [
      {
        id: "sub-g042-shops",
        jobId: "job-g042",
        name: "Architectural Casework Shop Drawings",
        type: "Shop Drawings",
        status: "Approved",
        revision: 1,
        dueDate: "2026-03-29",
        submittedDate: "2026-03-27",
        returnedDate: "2026-04-03",
        owner: "Pat",
        releaseBlocker: true,
        notes: "Approved package stored in job files."
      },
      {
        id: "sub-g042-hardware",
        jobId: "job-g042",
        name: "Hardware Schedule",
        type: "Hardware",
        status: "Approved as Noted",
        revision: 0,
        dueDate: "2026-04-01",
        submittedDate: "2026-03-28",
        returnedDate: "2026-04-05",
        owner: "Pat",
        releaseBlocker: true,
        notes: "Update keyed lock notes before fab release."
      }
    ],
    files: [
      {
        id: "file-1",
        ownerType: "job",
        ownerId: "job-g042",
        slot: "contract",
        name: "Executed Contract.pdf",
        uploadedAt: "2026-03-18"
      },
      {
        id: "file-2",
        ownerType: "job",
        ownerId: "job-g042",
        slot: "submittals",
        name: "Approved Submittals.zip",
        uploadedAt: "2026-04-03"
      }
    ],
    activity: [
      {
        id: "act-1",
        ownerType: "job",
        ownerId: "job-g042",
        author: "Geoff",
        message: "CO-001 approved and added to current contract.",
        createdAt: "2026-04-21"
      },
      {
        id: "act-2",
        ownerType: "job",
        ownerId: "job-g042",
        author: "Pat",
        message: "Install window confirmed with GC.",
        createdAt: "2026-05-06"
      }
    ]
  },
  {
    id: "job-g060",
    jobNumber: "G26-060",
    workType: "Bid / ITB",
    pm: "Geoff",
    client: "Mortenson",
    projectName: "Q4 Commercial Casework Package",
    baseContract: 600000,
    bidRef: "Q-26-060",
    awardDate: "2026-05-08",
    ntpDate: "2026-05-08",
    backlogStatus: "Awarded / Waiting",
    forecastStart: "2026-11-01",
    forecastEnd: "2027-01-31",
    forecastQuarter: "Q4 2026 / Q1 2027",
    expectedFabStart: "2026-10-05",
    expectedCompletion: "2027-01-31",
    fabStatus: "Not Started",
    installStart: "2026-11-01",
    installEnd: "2027-01-31",
    installStatus: "Ready",
    invoiceStatus: "Not Billed",
    crewSize: 6,
    gc: "Mortenson",
    notes: "Awarded 05/08/26. Future backlog: expected Q4 2026 or Q1 2027 release/install window.",
    changeOrders: [],
    purchaseOrders: [],
    submittals: [
      {
        id: "sub-g060-shops",
        jobId: "job-g060",
        name: "Casework Shop Drawings",
        type: "Shop Drawings",
        status: "In Progress",
        revision: 0,
        dueDate: "2026-05-20",
        owner: "Drafter",
        releaseBlocker: true,
        notes: "Needed before material release and long lead purchasing."
      },
      {
        id: "sub-g060-samples",
        jobId: "job-g060",
        name: "Finish Samples",
        type: "Finish Samples",
        status: "Not Started",
        revision: 0,
        dueDate: "2026-05-27",
        owner: "Estimator",
        releaseBlocker: true,
        notes: "Confirm laminate, solid surface, and hardware selections."
      }
    ],
    files: [],
    activity: [
      {
        id: "act-3",
        ownerType: "job",
        ownerId: "job-g060",
        author: "Evan",
        message: "Awarded $600k commercial casework job; carrying in contract backlog until release.",
        createdAt: "2026-05-08"
      }
    ]
  },
  {
    id: "job-g051",
    jobNumber: "G26-051",
    workType: "Bid / ITB",
    pm: "Geoff",
    client: "Banner Health",
    projectName: "Hospital Lab Phase 1",
    baseContract: 214000,
    bidRef: "Q-26-051",
    awardDate: "2026-06-12",
    ntpDate: "2026-06-12",
    backlogStatus: "Ready to Install",
    forecastStart: "2026-08-03",
    forecastEnd: "2026-08-07",
    forecastQuarter: "Q3 2026",
    expectedFabStart: "2026-07-13",
    expectedCompletion: "2026-08-07",
    fabStatus: "Ready",
    installStart: "2026-08-03",
    installEnd: "2026-08-07",
    installStatus: "Ready",
    invoiceStatus: "Not Billed",
    crewSize: 4,
    gc: "Layton",
    notes: "Hospital lab casework install currently stacked into the first week of August.",
    changeOrders: [],
    purchaseOrders: [],
    submittals: [],
    files: [],
    activity: [
      {
        id: "act-g051",
        ownerType: "job",
        ownerId: "job-g051",
        author: "System",
        message: "Added to capacity forecast for August install planning.",
        createdAt: "2026-05-09"
      }
    ]
  },
  {
    id: "job-p043",
    jobNumber: "P26-043",
    workType: "Bid / ITB",
    pm: "Pat",
    client: "McCarthy",
    projectName: "Science Building Casework",
    baseContract: 176000,
    bidRef: "Q-26-043",
    awardDate: "2026-06-18",
    ntpDate: "2026-06-18",
    backlogStatus: "Ready to Install",
    forecastStart: "2026-08-04",
    forecastEnd: "2026-08-06",
    forecastQuarter: "Q3 2026",
    expectedFabStart: "2026-07-20",
    expectedCompletion: "2026-08-06",
    fabStatus: "Ready",
    installStart: "2026-08-04",
    installEnd: "2026-08-06",
    installStatus: "Ready",
    invoiceStatus: "Not Billed",
    crewSize: 3,
    gc: "McCarthy",
    notes: "Overlaps Hospital Lab Phase 1 and should trigger a capacity warning.",
    changeOrders: [],
    purchaseOrders: [],
    submittals: [],
    files: [],
    activity: [
      {
        id: "act-p043",
        ownerType: "job",
        ownerId: "job-p043",
        author: "System",
        message: "Added to capacity forecast for August install planning.",
        createdAt: "2026-05-09"
      }
    ]
  },
  {
    id: "job-s2601",
    jobNumber: "S26-001",
    workType: "Service",
    pm: "Service",
    client: "Banner Health",
    projectName: "Clinic Countertop Repair",
    baseContract: 1200,
    awardDate: "2026-05-06",
    ntpDate: "2026-05-06",
    backlogStatus: "Ready to Install",
    forecastStart: "2026-05-14",
    forecastEnd: "2026-05-14",
    forecastQuarter: "Q2 2026",
    fabStatus: "Ready",
    installStart: "2026-05-14",
    installEnd: "2026-05-14",
    installStatus: "Ready",
    invoiceStatus: "Not Billed",
    crewSize: 1,
    gc: "Direct Client",
    serviceScope: "Replace small countertop section and repair edge banding.",
    requestedDate: "2026-05-06",
    scheduledDate: "2026-05-14",
    assignedTo: "Shop / Field",
    notes: "Quick service quote accepted by facilities contact.",
    finalCost: 725,
    changeOrders: [],
    purchaseOrders: [],
    submittals: [],
    files: [],
    activity: [
      {
        id: "act-s1",
        ownerType: "job",
        ownerId: "job-s2601",
        author: "Evan",
        message: "Service quote accepted and scheduled.",
        createdAt: "2026-05-06"
      }
    ]
  },
  {
    id: "job-s2602",
    jobNumber: "S26-002",
    workType: "Service",
    pm: "Service",
    client: "Scottsdale Unified",
    projectName: "Cabinet Door Replacement",
    baseContract: 650,
    awardDate: "2026-05-03",
    ntpDate: "2026-05-03",
    backlogStatus: "Complete",
    forecastStart: "2026-05-08",
    forecastEnd: "2026-05-08",
    forecastQuarter: "Q2 2026",
    fabStatus: "Complete",
    installStart: "2026-05-08",
    installEnd: "2026-05-08",
    installStatus: "Completed",
    invoiceStatus: "Paid",
    crewSize: 1,
    gc: "Direct Client",
    serviceScope: "Build and install replacement cabinet door.",
    requestedDate: "2026-05-02",
    scheduledDate: "2026-05-08",
    assignedTo: "Field",
    notes: "Small service job complete and paid.",
    finalCost: 390,
    changeOrders: [],
    purchaseOrders: [],
    submittals: [],
    files: [],
    activity: [
      {
        id: "act-s2",
        ownerType: "job",
        ownerId: "job-s2602",
        author: "Service",
        message: "Door replacement completed and invoice paid.",
        createdAt: "2026-05-08"
      }
    ]
  }
];

export const fileSlots = [
  "drawings",
  "specs",
  "schedule",
  "proposal",
  "contract",
  "submittals",
  "purchase orders",
  "vendor quotes",
  "stone invoices",
  "co docs",
  "photos",
  "invoices",
  "misc"
];
