insert into public.pricing_library_items (category, description, unit_cost, uom) values
('Cab Adds - 5-Knuckle Hinges', 'Touch Latch Per Door, Installed', 14, 'ea.'),
('Cab Adds - 5-Knuckle Hinges', '5-Knuckle Hinges and Catches, FH', 25, 'lin. ft'),
('Cab Adds - 5-Knuckle Hinges', '5-Knuckle Hinges and Catches, Lower', 19, 'lin. ft'),
('Cab Adds - 5-Knuckle Hinges', '5-Knuckle Hinges and Catches, Upper', 19, 'lin. ft'),
('Cab Adds - 5-Knuckle Hinges', '5-Knuckle Hinges and Catches, FH Stainless Steel', 31, 'lin. ft'),
('Cab Adds - 5-Knuckle Hinges', '5-Knuckle Hinges and Catches, Lower Stainless Steel', 27, 'lin. ft'),
('Cab Adds - 5-Knuckle Hinges', '5-Knuckle Hinges and Catches, Upper Stainless Steel', 27, 'lin. ft'),
('Cab Adds - Locks', 'z-DigiLock, Door', 190, 'ea.'),
('Cab Adds - Locks', 'z-DigiLock, Drawer', 214, 'ea.'),
('Cab Adds - Locks', 'Kitlocks, Installed', 148, 'ea.'),
('Cab Adds - Locks', 'Best Locks, Installed', 122, 'ea.'),
('Cab Adds - Locks', 'Simplex locks, Installed', 190, 'ea.'),
('Cab Adds - Locks', 'Door Cam Locks, Installed', 51, 'ea.'),
('Cab Adds - Locks', 'Keyless 1 Locks, Installed', 188, 'ea.'),
('Cab Adds - Locks', 'Drawer Cam Locks, Installed', 68, 'ea.'),
('Cab Adds - Locks', 'Tot Lok Magnetic Locks, Drw', 73, 'ea.'),
('Cab Adds - Locks', 'Tot Lok Magnetic Locks, Door', 62, 'ea.'),
('Cab Adds - Locks', 'Olympus Door Locks, Installed', 86, 'ea.'),
('Cab Adds - Locks', 'Comb-Cam Door Locks, Installed', 62, 'ea.'),
('Cab Adds - Locks', 'z-DigiLock, Shipping, One Lock', 28, 'ea.'),
('Cab Adds - Locks', 'Olympus Drawer Locks, Installed', 98, 'ea.'),
('Cab Adds - Locks', 'Comb-Cam Drawer Locks, Installed', 68, 'ea.'),
('Cab Adds - Locks', 'z-DigiLock, User Key (1 Req''d. per job)', 24, 'ea.'),
('Cab Adds - Locks', 'z-DigiLock, Manager Key (1 Req''d. per job)', 45, 'ea.'),
('Cab Adds - Locks', 'z-DigiLock, Program Key (1 Req''d. per job)', 53, 'ea.'),
('Cab Adds - Tackboards', 'Tackboards, Installed', 24, 'sq. ft.'),
('Cab Adds - Tackboards', 'Tacwall, Cut Charge, per lineal ft.', 6, 'lin. ft'),
('Cab Adds - Tackboards', 'Tacwall #2166, 1/4" x 48"w (4 lb/lf.- ships by truck)', 31, 'lin. ft'),
('Cabinets - Cabs Drawer Peds', 'Slide-Out Shelf', 102, 'ea.'),
('Cabinets - Cabs Drawer Peds', 'Drawer Ped, 4 Drw.', 554, 'ea.'),
('Cabinets - Cabs Drawer Peds', 'Drawer Ped, 5 Drw.', 598, 'ea.'),
('Cabinets - Cabs Drawer Peds', 'Pencil drawer, 2"-3"h', 116, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Oversize Drawer (36"w)', 37, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, 2 Drw., F/F', 466, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, Finished Top', 73, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, 3 Drw., B/B/F', 507, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, Finished Back', 73, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, Hvy Duty Slides', 37, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Pencil Drawer, Herman Miller', 92, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped_1 Drw. Printer Cab', 365, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Flat File, 5 drw., 48"w x 30"d', 1219, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Flat File, 6 drw., 48"w x 30"d', 1311, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Additional 6" Drawer, Accuride Slide', 79, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Base for Bench, 1 Drw., 36"+/-w', 487, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', '2-Drawer Rolling Ped w/(2) Drawer Locks', 829, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', '3-Drawer Rolling Ped w/(3) Drawer Locks', 896, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, 4 Drw. w/Pull-Out Breadboard', 591, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Lateral File Cabinet, 2 Drw. w/Suspended Files', 563, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Lateral File Cabinet, 3 Drw. w/Suspended Files', 636, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Drawer Ped, 3 Drw., B/B/F,w/Pull-Out Breadboard', 518, 'ea.'),
('Est-Cabinets - Cabs Drawer Peds', 'Lateral File Cabinet, 2 Drw.+2 Drw w/Suspended Files', 665, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Fin. Sides @ FH Cab', 182, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Full Ht. Cab over 24"d', 31, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'F.H. Open, Mel., 12"-16"d', 122, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'F.H. Open, Plam, 12"-16"d', 244, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'Full Ht. Cab w/Doors, 12"d', 233, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'F.H. Open, Mel., 12"d or less', 116, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'F.H. Open, Mel., 16"d or more', 146, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'F.H. Open, Plam, 12"d or less', 201, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'F.H. Open, Plam, 16"d or more', 256, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'Full Ht. Cab w/Doors, 12"-16"d', 274, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'Full Ht. Cab w/Doors, 16"-24"d', 287, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'Full Ht. Cab w/2-High Doors-ADD', 61, 'lin. ft'),
('Est-Cabinets - Cabs Full Height', 'Locker FH w/Door & Key Lock, 12"d', 440, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Locker 2-high w/Doors & Key Lock, 12"d', 573, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Support/Divider Panel, FH, 3/4"t, Plam', 159, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Locker 3-high w/Doors w/Padlock Hasp, 12"d', 640, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Locker 4-high w/Doors w/Padlock Hasp, 12"d', 770, 'ea.'),
('Est-Cabinets - Cabs Full Height', 'Refridgerator Trim Kit for Panels, Hardware Only, Installed', 671, 'ea.'),
('Est-Cabinets - Cabs Lower - Open', 'CPU Shelf/Cabinet', 121, 'ea.'),
('Est-Cabinets - Cabs Lower - Open', 'Open Lowers w/Plam Interior, 34"-36"h', 165, 'lin. ft'),
('Est-Cabinets - Cabs Lower - Open', 'Open Lowers, Melamine Interior, DEDUCT', 23, 'lin. ft'),
('Est-Cabinets - Cabs Lower - Open', 'Open Lowers w/Plam Interior w/Drawer, 34"-36"h', 201, 'lin. ft'),
('Est-Cabinets - Cabs Lower - Open', 'Open Locker Cubbies, Plam Interior & Top 14" tall', 110, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'New 4" Kick', 37, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers over 24"d', 13, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers w/Doors, 34"-36"h', 155, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Finished End @ Lower Cabinet', 48, 'ea.'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Finished Back @ Lower Cabinet', 48, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers Sink Cab. Suspended ~6"', 61, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers w/Doors & Drws, 34"-36"H', 187, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Filler Panel @ Lower, 3/4"t, Plam', 61, 'ea.'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers Sink Cab. w/Doors, 34"-36"h', 152, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Rev-A-Shelf Pull-Out Hamper, Installed', 609, 'ea.'),
('Est-Cabinets - Cabs Lowers w/Doors', '155Lowers Sink Cab. w/Doors, 34"-36"h, ADA w/o Kick', 189, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers Sink Cab. w/Doors, 34"-36"h, ADA w/Attached Kick', 217, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers Sink Cab., 34"-36"h, ADA w/Removable Angled Panel', 199, 'lin. ft'),
('Est-Cabinets - Cabs Lowers w/Doors', 'Lowers Sink Cab. w/Doors, 34"-36"h, ADA w/Removable Shelf & Kick', 199, 'lin. ft'),
('Est-Cabinets - Cabs Uppers - Open', 'Open Uppers, 24"-32"h', 92, 'lin. ft'),
('Est-Cabinets - Cabs Uppers - Open', 'Open Uppers, 32"-38"h', 98, 'lin. ft'),
('Est-Cabinets - Cabs Uppers - Open', 'Open Uppers, 24"h or less', 88, 'lin. ft'),
('Est-Cabinets - Cabs Uppers - Open', 'Open Uppers, 38"h or more', 102, 'lin. ft'),
('Est-Cabinets - Cabs Uppers - Open', 'Open Uppers, Melamine Interior, DEDUCT', 20, 'lin. ft'),
('Est-Cabinets - Cabs Uppers - Open', 'Open Uppers, Microwave Shelf, Plam Interior', 115, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Light Valence', 13, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', '12"+ to 16"d upper', 11, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', '16"+ to 24"d upper', 16, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Soffit Panels, Angled', 61, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers, Plam Interior', 23, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers w/Doors, 24"-32"h', 125, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers w/Doors, 32"-38"h', 135, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Upper Corner Cabinet Add-On', 159, 'ea.'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers w/Doors, 24" or less', 118, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Finished End @ Upper Cabinet', 48, 'ea.'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Finished Top @ Upper Cabinet', 48, 'ea.'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers w/Doors, 38"h or more', 141, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Finished Bottom @ Upper Cabinet', 48, 'ea.'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Soffit Panels, 12"-18" Straight', 43, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Filler Panel @ Upper, 3/4"t, Plam', 61, 'ea.'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Soffit Panels, Jurgens'' w/Reveals', 48, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Soffit Panels, Angled w/Inside Corner', 73, 'ea.'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers w/Doors - Microwave Opening /Plam', 232, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Soffit Panels, Vert. Wood Grain Plam -ADD', 10, 'lin. ft'),
('Est-Cabinets - Cabs Uppers w/Doors', 'Uppers w/Doors, 32"-38"h, Angled for Corner', 238, 'lin. ft'),
('Est-Cabinets - Closet Packs', 'Closet Pack, ADA', 494, 'ea.'),
('Est-Cabinets - Closet Packs', 'Closet Center Support', 79, 'ea.'),
('Est-Cabinets - Closet Packs', 'Closet Pack, Plam, 4''', 305, 'ea.'),
('Est-Cabinets - Closet Packs', 'Closet Pack Additional Footage', 31, 'lin. ft'),
('Est-Cabinets - Closet Packs', 'Closet Pack, Mel. w/Plam Edge, 4''', 244, 'ea.'),
('Est-Cabinets - Doors', 'Lower, Sliding Doors', 25, 'lin. ft'),
('Est-Cabinets - Doors', 'Upper, Sliding Doors', 22, 'lin. ft'),
('Est-Cabinets - Doors', 'Open Uppers_Plam Interior', 116, 'lin. ft'),
('Est-Cabinets - Doors', 'Lower, Simple Pocket Doors', 427, 'set'),
('Est-Cabinets - Doors', 'Upper, Simple Pocket Doors', 427, 'set'),
('Est-Cabinets - Doors', 'Glass Doors, per Door +Glass', 117, 'ea.'),
('Est-Cabinets - Doors', 'Glass Doors, FH, per Door +Glass', 184, 'ea.'),
('Est-Cabinets - Doors', 'Blum Flip-Up Hinge Kit, Installed', 385, 'pair'),
('Est-Cabinets - Doors', 'Gate W/Bommer Hinge 1" to 1-1/2", Installed', 1092, 'ea.'),
('Est-Cabinets - Doors', 'Flip-Up, Pocket-type Door Hardware, Swing-Up Fitting', 79, 'pair'),
('Est-Cabinets - Misc.', 'Trash Opening, Short Door', 49, 'ea.'),
('Est-Cabinets - Misc.', 'File Bars, Set , Installed', 31, 'ea.'),
('Est-Cabinets - Misc.', '1/4" Plex Divider, Square edge', 15, 'ea.'),
('Est-Cabinets - Misc.', '1/4" P-Lam Divider, Square edge', 13, 'ea.'),
('Est-Cabinets - Misc.', '1/4" Masonite Divider, Square edge', 10, 'ea.'),
('Est-Cabinets - Misc.', 'Non-White Melamine Cabinet Interior', 4, 'lin. ft'),
('Est-Cabinets - Misc.', '1/4" Masonite Divider, Rad/Scoop edge', 18, 'ea.'),
('Est-Cabinets - Misc.', 'Trash Opening in Door Sq. w/St. Steel Channel', 122, 'ea.'),
('Est-Cabinets - Misc.', 'Trash Opening in Door, Rad./Plam Interior of Cab', 102, 'ea.'),
('Est-Cabinets - Misc.', 'Perforated Metal for AV Base Cabinet Door, Installed', 122, 'ea.'),
('Est-Cabinets - Misc.', 'Mail Slot, Wall Mt., ADD ON Adj. Dividers, 12"d x 34"h +dividers', 103, 'lin. ft'),
('Est-Cabinets - Misc.', 'Mail Slots @ T-Top ADD ON for Mel/Masonite Dividers, 12"d x 15"h', 88, 'lin. ft'),
('Est-Cabinets - Misc.', 'Mail Slot, Wall Mt., ADD ON Fixed Dividers, 12"d x 34"h +dividers', 110, 'lin. ft'),
('Est-Cabinets - Shelving', 'KV Brackets', 14, 'ea.'),
('Est-Cabinets - Shelving', 'Shelf, 18"-24"w, Plam', 32, 'lin. ft'),
('Est-Cabinets - Shelving', 'KV #87, Hvy Dty Standards', 37, 'ea.'),
('Est-Cabinets - Shelving', 'Shelf, 12"+ to 18"w, Plam', 24, 'lin. ft'),
('Est-Cabinets - Shelving', 'Shelf, 12"-18"w, Melamine', 19, 'lin. ft'),
('Est-Cabinets - Shelving', 'Shelf, 12"w or Less, Plam', 22, 'lin. ft'),
('Est-Cabinets - Shelving', 'Shelf, 18"-24"w, Melamine', 22, 'lin. ft'),
('Est-Cabinets - Shelving', 'Shelf, 12"w or less, Melamine', 16, 'lin. ft'),
('Est-Cabinets - Shelving', 'Installation, Standards & Brackets', 106, 'hr.'),
('Est-Counters - Angles, Curves, Wood E', 'Add Angle', 58, 'ea.'),
('Est-Counters - Angles, Curves, Wood E', 'Wood Edge', 35, 'lin. ft'),
('Est-Counters - Angles, Curves, Wood E', 'Dropped Counter', 122, 'ea.'),
('Est-Counters - Angles, Curves, Wood E', 'Add Plywood Core', 7, 'lin. ft'),
('Est-Counters - Angles, Curves, Wood E', 'Skirt, 6"h, Plam', 24, 'lin. ft'),
('Est-Counters - Angles, Curves, Wood E', 'Add Radius Corner', 37, 'ea.'),
('Est-Counters - Angles, Curves, Wood E', 'Add Radius/Curves', 37, 'lin. ft'),
('Est-Counters - Angles, Curves, Wood E', 'Wood Edge, Radiused', 75, 'lin. ft'),
('Est-Counters - Angles, Curves, Wood E', 'Add 45o Inside Corner', 58, 'ea.'),
('Est-Counters - Angles, Curves, Wood E', 'Add-Chem Resistant Plam', 6, 'sq. ft.'),
('Est-Counters - Angles, Curves, Wood E', 'C-Top Height Change, ADA', 180, 'ea.'),
('Est-Counters - Angles, Curves, Wood E', 'Wood Edge, Radiused Corner', 122, 'ea.'),
('Est-Counters - Angles, Curves, Wood E', 'C-Top - Add for Marine Grade Ply @ Sink', 13, 'lin. ft'),
('Est-Counters - Angles, Curves, Wood E', 'Bent 18ga. Stainless Steel Backsplash Cover, 48"+/-, Installed', 170, 'ea.'),
('Est-Counters - Grommets', 'Grommet, Installed', 19, 'ea.'),
('Est-Counters - Grommets', 'Trash Rings, 4"-6"', 92, 'ea.'),
('Est-Counters - Grommets', 'Trash Rings, 8" Installed', 104, 'ea.'),
('Est-Counters - Grommets', 'Trash Rings, 12" Installed', 152, 'ea.'),
('Est-Counters - Plam C-Tops', 'Full Height Splash', 24, 'lin. ft'),
('Est-Counters - Plam C-Tops', 'C-Top w/4" Splash, 36""d', 61, 'lin. ft'),
('Est-Counters - Plam C-Tops', 'C-Top w/4" Splash, 25.5"-33"d', 55, 'lin. ft'),
('Est-Counters - Plam C-Tops', 'C-Top w/4" Splash, Up to 25.5"d', 55, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'C-Top w/Splash, 36"d, 1" w/3mm PVC/T-Mould Edge', 68, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'C-Top w/o Splash, 36"d, 1" w/3mm PVC/T-Mould Edge', 68, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'C-Top w/Splash, 25.5"-33"d, 1" w/3mm PVC/T-Mould Edge', 68, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'C-Top w/o Splash, 25.5"-33"d, 1" w/3mm PVC/T-Mould Edge', 55, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'C-Top w/o Splash, Up to 25"d, 1" w/3mm PVC/T-Mould Edge', 55, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'C-Top w/4" Splash, Up to 25.5"d, 1" w/3mm PVC/T-Mould Edge', 55, 'lin. ft'),
('Est-Counters - Plam C-Tops w/3mm PV', 'Post Formed C-Top, 25"w w/Splash, Str. Edge, 3mm PVC/T-Mould Edge', 43, 'lin. ft'),
('Est-Counters - Plam C-Tops w/o Splash', 'C-Top w/o Splash, 36"d', 65, 'lin. ft'),
('Est-Counters - Plam C-Tops w/o Splash', 'C-Top w/o Splash, 25.5"-33"d', 61, 'lin. ft'),
('Est-Counters - Plam C-Tops w/o Splash', 'C-Top w/o Splash, Up to 25.5"d', 55, 'lin. ft'),
('Est-Counters - Plam C-Tops w/o Splash', 'C-Top w/o Splash, 25.5"-33"d - Linoleum', 80, 'lin. ft'),
('Est-Counters - Post Formed C-tops', 'Post-Formed Countertop Pick-Up', 100, 'hr.'),
('Est-Counters - Post Formed C-tops', 'Post Formed C-Top, 25"w w/Splash, Str. Edge', 35, 'lin. ft'),
('Est-Counters - Post Formed C-tops', 'Post Formed C-Top, 25"w w/Splash, Rad. Drop Edge', 37, 'lin. ft'),
('Est-Counters - Post Formed C-tops', 'Post Formed C-Top, 25"w w/Splash, 180o Bullnose Edge', 30, 'lin. ft'),
('Est-Counters - Post Formed C-tops', 'Post Formed C-Top, 30"w w/o Splash, 180o Bullnose Edge', 32, 'lin. ft'),
('Est-Counters - Post Formed C-tops', 'Post Formed C-Top, 36"w w/o Splash, 180o Bullnose edge', 39, 'lin. ft'),
('Est-Counters - Post Formed C-tops', 'Post Formed C-Top, 25"w w/Splash, No Drip Edge, Installed', 30, 'lin. ft'),
('Est-Counters - Solid Surface', 'Skirt, 6"h, Corian', 88, 'lin. ft'),
('Est-Counters - Solid Surface', 'Corian, Integral Sink', 696, 'ea.'),
('Est-Counters - Solid Surface', 'Corian Base, 4", Installed', 83, 'lin. ft'),
('Est-Counters - Solid Surface', 'Corian Countertop, Template', 13, 'ea.'),
('Est-Counters - Solid Surface', 'Solid Surface Transaction Top', 154, 'lin. ft'),
('Est-Counters - Solid Surface', 'Corian Countertop, Coved End Splash', 385, 'ea.'),
('Est-Counters - Solid Surface', 'Corian Countertop w/Coved Backsplash', 317, 'lin. ft'),
('Est-Counters - Solid Surface', 'Corian Countertop, No-Drip Front Edge', 177, 'lin. ft'),
('Est-Counters - Solid Surface', 'Corian Countertop, Coved Backsplash Inside Corner', 114, 'ea.'),
('Est-Counters - Solid Surface', 'Corian Countertop, Coved Backsplash Applied End Splash', 108, 'ea.'),
('Est-Counters - Solid Surface', 'Corian Countertop, No-Drip Front Edge, Rad.Inside Corner', 171, 'ea.'),
('Est-Counters - Solid Surface', 'Corian Counter, Undermount Stainless Steel Sink, Cut/Finish Hole', 190, 'ea.'),
('Est-Counters - Solid Surface', '1 - Solid Surface C-Top', 234, 'lin. ft'),
('Est-Counters - Sub-Tops', 'C-Top Sub-Top for Solid Surface or Stone', 29, 'lin. ft'),
('Est-Counters - Sub-Tops', 'T-Top Sub-Top for Solid Surface or Stone', 24, 'lin. ft'),
('Est-Counters - Sub-Tops', 'C-Top Sub-Top for Solid Surface or Stone, Radiused', 37, 'lin. ft'),
('Est-Counters - Sub-Tops', 'T-Top Sub-Top for Solid Surface or Stone, Radiused', 30, 'lin. ft'),
('Est-Counters - Supports', 'Plam Corbel', 121, 'ea.'),
('Est-Counters - Supports', 'Gambas Support Bracket', 68, 'ea.'),
('Est-Counters - Supports', 'Support Panel, 3/4"t, Plam', 104, 'ea.'),
('Est-Counters - Supports', 'Metal Support Leg, Installed', 222, 'ea.'),
('Est-Counters - Supports', 'Support Panel, 1-1/2"t, Plam', 146, 'ea.'),
('Est-Counters - Supports', 'Transaction Top Support Panel', 55, 'ea.'),
('Est-Counters - Supports', 'In-Wall Bracket, Installed by GC', 98, 'ea.'),
('Est-Counters - Supports', 'Support Panel, 3/4" Plam, Angled', 122, 'ea.'),
('Est-Counters - Supports', 'Support Panel, 3/4" Plam, Curved', 183, 'ea.'),
('Est-Counters - Supports', 'In-Die-Wall Bracket, Installed by F&S', 98, 'ea.'),
('Est-Counters - Supports', 'In-Wall, Bracket, 2.5x2.5x 1/4 Welded C-Top Support w/Foot', 214, 'ea.'),
('Est-Counters - Transaction Tops', 'T-Top, Add Angle', 61, 'ea.'),
('Est-Counters - Transaction Tops', 'T-Top, Add Radius/Curve', 36, 'lin. ft'),
('Est-Counters - Transaction Tops', 'T-Top, up to 16"d, 1" w/PVC Edge', 46, 'lin. ft'),
('Est-Counters - Transaction Tops', 'T-Top, Plam Self-Edge, up to 16"w', 44, 'lin. ft'),
('Est-Counters - Transaction Tops', 'T-Top, Plam T-Mould edge, up to 16"w', 44, 'lin. ft'),
('Est-Counters - Transaction Tops', 'T-Top, Rad. w/Wood Edges & 12"h Face, Installed', 262, 'lin. ft'),
('Est-Fixtures - Office', 'Access Panels', 100, 'ea.'),
('Est-Fixtures - Office', 'Die Wall, Curved w/Plam', 183, 'lin. ft'),
('Est-Fixtures - Office', 'Access Panels, Curved DW', 168, 'ea.'),
('Est-Fixtures - Office', 'Plam Inlaid Squares @ DW', 55, 'ea.'),
('Est-Fixtures - Office', 'Die Wall, Straight w/Plam', 152, 'lin. ft'),
('Est-Fixtures - Office', '4''6x2''0x1 1/2" Plam Divider', 365, 'ea.'),
('Est-Fixtures - Office', 'P-Lam Panels w/Reveals @ DW', 207, 'lin. ft'),
('Est-Fixtures - Office', 'Modesty Panel, 2-Sided, Plam', 61, 'lin. ft'),
('Est-Fixtures - Office', 'Metal Laminate Kick @ Die Wall', 38, 'lin. ft'),
('Est-Fixtures - Office', 'Die Wall, T-Top Panel, Str. w/Plam', 97, 'lin. ft'),
('Est-Fixtures - Office', 'Die Wall, T-Top Panel, Curved w/Plam', 146, 'lin. ft'),
('Est-Fixtures - Office', '4''6x3''6x4" Divider Panel w/TB on 2 Sides', 740, 'ea.'),
('Est-Fixtures - Office', 'In-Die-Wall Steel Post, Installed by F&S', 183, 'ea.'),
('Est-Fixtures - Office', 'Angled Plam Panels w/Painted Reveals @ DW', 101, 'lin. ft'),
('Est-Fixtures - Office', 'Stainless Steel Cornerguard @ Divider Panel', 104, 'ea.'),
('Est-Fixtures - Office', 'Veneered Wood Panels w/Painted Reveals @ DW', 287, 'lin. ft'),
('Est-Fixtures - Office', 'Aluminum Channel, 1/2" Reveal, Curved, Installed', 37, 'lin. ft'),
('Est-Fixtures - Office', 'Aluminum Channel, 1/2" Reveal, Straight, Installed', 25, 'lin. ft'),
('Est-Fixtures - Office', 'Angled Plam Panels w/Painted Reveals @ DW, Radiused', 152, 'lin. ft'),
('Est-Fixtures - Office', 'Str. Plam Panels, "3-Color Wave" w/Painted Reveals @ DW', 243, 'lin. ft'),
('Est-Fixtures - Office', 'Curved Plam Panels, "3-Color Wave" w/Painted Reveals @ Curved DW', 280, 'lin. ft'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication', 100, 'hr.'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication, Labor, D/T', 156, 'hr.'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication, Labor, O/T', 156, 'hr.'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication, Apply Veneer', 100, 'hr.'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication, Solid Surface', 100, 'hr.'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication, Apply Plastic Laminate', 100, 'hr.'),
('Est-Labor - Custom Fabrication', 'Custom Fabrication, Solid Surface - Integral Sink', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Delivery, Load', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Delivery, Unload', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Downtown Parking', 40, 'day'),
('Est-Labor - Delivery & Installation', 'Union Installation', 155, 'hr.'),
('Est-Labor - Delivery & Installation', 'Delivery, Drive, R/T', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Demo, Form & Structure', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Installation, D/T Hrs.', 155, 'hr.'),
('Est-Labor - Delivery & Installation', 'Installation, O/T Hrs.', 145, 'hr.'),
('Est-Labor - Delivery & Installation', 'Delivery Material Pick Up', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Installation, Travel, R/T', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Installation, Form & Structure', 100, 'hr.'),
('Est-Labor - Delivery & Installation', 'Installation, Prevailing Wage Filing Fee', 58, 'ea.'),
('Est-Labor - Delivery & Installation', 'Installation, Prevailing Wage Hrs.+ Filing Fee', 155, 'hr.'),
('Est-Labor - Engineering/PM', 'CNC Pathing', 100, 'hr.'),
('Est-Labor - Engineering/PM', 'Site Survey', 100, 'hr.'),
('Est-Labor - Engineering/PM', 'Project Management', 100, 'hr.'),
('Est-Labor - Engineering/PM', 'Submittal Drawings', 100, 'hr.'),
('Est-Labor - Engineering/PM', 'Project Management - LEEDS Tracking', 100, 'hr.'),
('Est-Labor - Finishing', 'Finish / Sand', 100, 'hr.'),
('Est-Labor - Finishing', 'Finish / Stain', 100, 'hr.'),
('Est-Labor - Finishing', 'Finish / Coating', 100, 'hr.'),
('Est-Labor - Finishing', 'Finish / Samples / Color Matching', 317, 'ea.'),
('Est-Labor - Parts / Milling', 'Mold Stock', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Plane Stock', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Mill S4S Stock', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Equipment Setup', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Hand Sand Stock', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Cut Parts to Length', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Table Saw, Rip Stock', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Sand Stock, Wide Belt', 100, 'hr.'),
('Est-Labor - Parts / Milling', 'Edge Sand on Table Saw', 100, 'hr.'),
('Est-Labor - Parts / Panel', 'CNC Routing', 100, 'hr.'),
('Est-Labor - Parts / Panel', 'Wide Belt, 1 Man', 100, 'hr.'),
('Est-Labor - Parts / Panel', 'Edge Band, Machine', 100, 'hr.'),
('Est-Labor - Parts / Panel', 'Panel Cutting_Beam Saw', 100, 'hr.'),
('Est-Labor - Parts / Panel', 'Point to Point Machining', 100, 'hr.'),
('Est-Labor - Parts / Panel', 'Edge Band, Detailing/Hand Band', 100, 'hr.'),
('Est-Library Advantage - PeaceHealth', 'Plam Chart Holder', 272, 'ea.'),
('Est-Library Advantage - Prov Irvington R', 'Loose Plam', 69, 'lot'),
('Est-Library Advantage - Prov Irvington R', 'Plam Door Faces', 92, 'ea.'),
('Est-Library Advantage - Prov Irvington R', 'Plam Refer Shelf', 92, 'ea.'),
('Est-Library Advantage - Prov Irvington R', 'Plam Drawer Faces', 81, 'ea.'),
('Est-Library Advantage - Prov Irvington R', 'C-Top Edge Re-Glue', 6, 'lin. ft'),
('Est-Library Advantage - Prov Irvington R', 'Demo, Form & Structure', 100, 'hr.'),
('Est-Library Advantage - Prov Irvington R', 'Misc. Repair Materials', 29, 'lot'),
('Est-Library Advantage - Prov Irvington R', 'End Panel, 3/4"t, Plam, G2S', 98, 'ea.'),
('Est-Library Advantage - Prov Irvington R', 'Installation, Form & Structure', 100, 'hr.'),
('Est-Library Advantage - Providence Sta', 'Suite Entry A/Type B1', 4508, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Suite Entry B/Type D1', 3922, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Suite Entry C/Type F1', 2910, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Suite Entry D/Type H1', 3163, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Suite Entry E/Type K1', 2740, 'ea.'),
('Est-Library Advantage - Providence Sta', '3/4"x12" Plam Chair Rail', 35, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Rad Plam Corner @ Die Wall', 115, 'ea.'),
('Est-Library Advantage - Providence Sta', '3/4"x6" Plam Coat Hook Board', 23, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Uppers w/Doors, 50"h or more', 144, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Solid Surface T-Top w/Back Bevel', 217, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Bobrick 76717 Coat Hook, Installed', 29, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Dbl Plam Valence @ Upper Glass Track', 58, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Solid Surface Trim @ DW w/Back Bevel', 95, 'lin. ft'),
('Est-Library Advantage - Providence Sta', '3-Drawer Rolling Ped w/(1) Drawer Lock', 782, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Solid Surface T-Top w/Back Bevel, Rad.', 288, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Solid Surface Edge Counter w/Back Bevel', 179, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Angled Plam Panels w/Painted Reveals @ DW', 96, 'lin. ft'),
('Est-Library Advantage - Providence Sta', '3'' Flip-Up Desk w/3mm C-Top Edge, Installed', 518, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Die Wall, Curved w/Maple Veneer Ext/Plam Int', 432, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Die Wall, Straight w/Maple Veneer Ext/Plam Int', 288, 'lin. ft'),
('Est-Library Advantage - Providence Sta', 'Solid Surface T-Top w/Back Bevel, Add Radius Corner', 115, 'ea.'),
('Est-Library Advantage - Providence Sta', 'Add Cut-Out on Upper Cabinet Bottom for PT Dispenser', 46, 'ea.'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Plam', 23, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Stainless Steel Base', 62, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Maple, 4" Stained', 25, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Maple, 6" Stained', 37, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Cherry, 4" Stained', 31, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Cherry, 6" Stained', 44, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Maple, 4" Clear Fin.', 20, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Maple, 6" Clear Fin.', 31, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Cherry, 4" Clear Fin.', 25, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Base, Cherry, 6" Clear Fin.', 37, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Chair Rail, Maple, 4" Clear Fin., Installed', 31, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'PG Wood Base, Installed Raw, Putty & Paint by Others', 19, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'MDF Pre Primed 11/16 x 5 1/2 x 16'' pcs Square edge', 1, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Pr-primed MDF Base, 4", Installed, Putty & Paint by Others', 19, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'Pr-primed MDF Base, 8", Installed, Putty & Paint by Others', 25, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Base', 'MDF Pre Primed 11/16 x 4 9/16 x 16'' pcs Square edge', 1.25, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Paneling', 'Plam Slatwall, w/Metal Inserts', 62, 'sq. ft.'),
('Est-Paneling/Base/Wall Cap - Paneling', 'Plam Paneling, Installed, Basic', 48, 'sq. ft.'),
('Est-Paneling/Base/Wall Cap - Paneling', 'MDF Paneling, Putty & Paint B.O.Installed', 25, 'sq. ft.'),
('Est-Paneling/Base/Wall Cap - Paneling', 'Wood Paneling, Clear Fin, Installed, Low End', 53, 'sq. ft.'),
('Est-Paneling/Base/Wall Cap - Paneling', 'Wood Paneling, Clear Fin, Installed, High End', 64, 'sq. ft.'),
('Est-Paneling/Base/Wall Cap - Wall Cap', 'Wall Cap, 3/4"', 31, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Wall Cap', 'Wall Cap, 1 1/2"', 40, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Wall Cap', 'Solid Surface Wall Cap, 4"w, Sq. Edges', 168, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Wall Cap', 'Solid Surface Sill, 1/2"x5"w, Sq. Edges', 122, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Wall Cap', 'Solid Surface Wall Cap, 6"w, Bull Nose + Sq. Edge', 215, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Window', 'MDF 3/4" Primed Window Sill', 24, 'lin. ft'),
('Est-Paneling/Base/Wall Cap - Window', 'MDF 3/4" Primed Window Sill and Skirt', 39, 'lin. ft'),
('Material-Edge Bands - ABS', '3mm ABS Edgebanding', 2, 'lin. ft'),
('Material-Edge Bands - ABS', '3mm ABS Siesmic Shelf Edgebanding', 2, 'lin. ft'),
('Material-Edge Bands - Plam', 'Plastic Laminte Edge Band', 7, 'lin. ft'),
('Material-Edge Bands - PVC', '3mm PVC', 1.5, 'lin. ft'),
('Material-Edge Bands - PVC', '3mm PVC for 1-1/2" C/T', 2.75, 'lin. ft');
